/*
   BCC
   Copyright (c) 2025 William Gibbs

   This software is provided 'as-is', without any express or implied
   warranty. In no event will the authors be held liable for any damages
   arising from the use of this software.

   Permission is granted to anyone to use this software for any purpose,
   including commercial applications, and to alter it and redistribute it
   freely, subject to the following restrictions:

   1. The origin of this software must not be misrepresented; you must not
      claim that you wrote the original software. If you use this software
      in a product, an acknowledgment in the product documentation would be
      appreciated but is not required.
   2. Altered source versions must be plainly marked as such, and must not be
      misrepresented as being the original software.
   3. This notice may not be removed or altered from any source distribution.
*/

#ifndef GLOBALS_H
#define GLOBALS_H


/** The contents of the concatenated file generated by BCC from input files. */
extern char *text;

/** The name given to the file generated by BCC. */
extern char *output_title;

/** True if '-S' flag was called–assembly is being returned. */
extern int return_asm;

#endif // GLOBALS_H